[toolchain]
anchor_version = "0.31.1"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solrush_dex = "HCkVnLDL76FR8JJ9fbWg67kr48AtNqDgsivSt19Dnu9c"

[programs.localnet]
solrush_dex = "HCkVnLDL76FR8JJ9fbWg67kr48AtNqDgsivSt19Dnu9c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/comprehensive-test.ts"
