[toolchain]
anchor_version = "0.31.0"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solrush_dex = "FZ25GUwrX9W5PxBe5Ep8fR1F3HzoSeGH61YvW8sBA8J1"

[programs.localnet]
solrush_dex = "FZ25GUwrX9W5PxBe5Ep8fR1F3HzoSeGH61YvW8sBA8J1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/comprehensive-test.ts"
